#port
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

#database

spring:
  jpa:
    generate-ddl : true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #swagger spring version over 2.6
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: secret

#logging
logging:
  level:
    com.ssafy.search: debug